radio/apps/programmes/urls.py
# Radioco - Broadcasting Radio Recording Scheduling system.
# Copyright (C) 2014  Iago Veloso Abalo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf.urls import patterns, url
from django.views.generic import ListView

from apps.programmes import views
from apps.programmes.feeds import RssProgrammeFeed
from apps.programmes.models import Programme

urlpatterns = patterns('',
   url(
       r'^$',
       ListView.as_view(
           queryset=Programme.objects.order_by('name'),
           template_name='programmes/programme_list.html'
       ),
       name='list'
   ),
   url(r'^(?P<slug>[-\w]+)/$', views.programme_detail, name='detail'),
   url(
       r'^(?P<slug>[-\w]+)/(?P<season_number>\d+)x(?P<episode_number>\d+)/$',
       views.episode_detail,
       name='episode_detail'
   ),
   url(r'^(?P<slug>[-\w]+)/rss/$', RssProgrammeFeed(), name='rss')
)

radio/configs/common/urls.py
# Radioco - Broadcasting Radio Recording Scheduling system.
# Copyright (C) 2014  Iago Veloso Abalo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _
from filebrowser.sites import site

admin.site.logout_template = 'radio/logged_out.html'
admin.site.site_header = _('RadioCo administration')
admin.site.site_title = _('RadioCo site admin')


def handler400(request):
    response = render_to_response('radio/400.html', {}, context_instance=RequestContext(request))
    response.status_code = 400
    return response


def handler404(request):
    response = render_to_response('radio/404.html', {}, context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler403(request):
    response = render_to_response('radio/403.html', {}, context_instance=RequestContext(request))
    response.status_code = 403
    return response


def handler500(request):
    response = render_to_response('radio/500.html', {}, context_instance=RequestContext(request))
    response.status_code = 500
    return response


urlpatterns = patterns('',
    url(r'^$', 'apps.radio.views.index', name="home"),
    url(r'^login/$', 'apps.radio.views.user_login', name="login"),
    url(r'^logout/$', 'apps.radio.views.user_logout', name="logout"),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^configuration/schedule_editor/', 'apps.dashboard.views.full_calendar', name="schedule_editor"),
    url(r'^schedules/', include('apps.schedules.urls', namespace="schedules")),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace="dashboard")),
    url(r'^programmes/', include('apps.programmes.urls', namespace="programmes")),
    url(r'^users/', include('apps.users.urls', namespace="users")),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^api/1/recording_schedules/$', 'apps.radio.views.recording_schedules', name="recording_schedules"),
    url(r'^api/1/radiocom/programmes', 'apps.api.views.programmes_json', name='programmes_json'),
    url(r'^api/1/radiocom/radiostation', 'apps.api.views.station_json', name='station_json'),
    url(r'^api/1/submit_recorder/$', 'apps.radio.views.submit_recorder', name="submit_recorder"),
    url(r'^api/2/', include('apps.api.urls', namespace="api"))
)

if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

# Media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Static
urlpatterns += staticfiles_urlpatterns()

radioco/apps/api/urls.py
from rest_framework import routers
from radioco.apps.api import views
from django.urls import include, re_path


router = routers.DefaultRouter(trailing_slash=False)
router.register(r'programmes', views.ProgrammeViewSet)
router.register(r'episodes', views.EpisodeViewSet)
router.register(r'schedules', views.ScheduleViewSet)
router.register(r'transmissions', views.TransmissionViewSet, basename='transmission')
router.register(r'operations', views.TransmissionOperationViewSet, basename='operation')

radiocom_router = routers.DefaultRouter(trailing_slash=False)
radiocom_router.register(r'programmes', views.RadiocomProgrammeViewSet, basename='radiocom_programmes')
radiocom_router.register(r'transmissions', views.RadiocomTransmissionViewSet, basename='radiocom_transmission')
radiocom_router.register(r'radiostation', views.RadiocomStation, basename='radiocom_radiostation')

urlpatterns = router.urls + [
    re_path(r'^radiocom/', include(radiocom_router.urls)),
]

radioco/configs/base/urls.py
# Radioco - Broadcasting Radio Recording Scheduling system.
# Copyright (C) 2014  Iago Veloso Abalo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf import settings
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils.translation import gettext_lazy as _
from django.views.i18n import JavaScriptCatalog
from filebrowser.sites import site

admin.site.logout_template = 'radioco/logged_out.html'
admin.site.site_header = _('RadioCo administration')
admin.site.site_title = _('RadioCo site admin')


### templates not implemented, led to strange exceptions when running tests.
# def handler400(request):
#    response = render_to_response('radioco/400.html', {}, context_instance=RequestContext(request))
#    response.status_code = 400
#    return response
#
#
# def handler404(request):
#    response = render_to_response('radioco/404.html', {}, context_instance=RequestContext(request))
#    response.status_code = 404
#    return response
#
#
# def handler403(request):
#    response = render_to_response('radioco/403.html', {}, context_instance=RequestContext(request))
#    response.status_code = 403
#    return response
#
#
# def handler500(request):
#    response = render_to_response('radioco/500.html', {}, context_instance=RequestContext(request))
#    response.status_code = 500
#    return response

js_info_dict = {
    'packages': ('recurrence',),
}

from radioco.apps.radioco.views import index, user_logout
from radioco.apps.api.recorder_views import recording_schedules, submit_recorder

urlpatterns = [
    re_path(r'^$', index, name="home"),
    re_path(r'^jsi18n/$', JavaScriptCatalog.render_to_response, js_info_dict, name='javascript-catalog'),
    re_path(r'^logout/$', user_logout, name="logout"),
    # re_path(r'^admin/filebrowser/', include(site.urls)),
    re_path(r'^admin/filebrowser/', site.urls),
    re_path(r'^grappelli/', include('grappelli.urls')),
    # re_path(r'^admin/', include(admin.site.urls)),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^admin/password_reset/$', auth_views.PasswordResetView.as_view(), name='admin_password_reset'),
    re_path(r'^admin/password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # url(r'^configuration/schedule_editor/', 'radioco.apps.dashboard.views.full_calendar', name="schedule_editor"),
    re_path(r'^schedules/', include(('radioco.apps.schedules.urls', 'schedules'), namespace="schedules"), name="schedules"),
    re_path(r'^programmes/', include(('radioco.apps.programmes.urls', 'programmes'), namespace="programmes"), name="programmes"),
    re_path(r'^users/', include(('radioco.apps.users.urls', 'users'), namespace="users"), name="users"),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    re_path(r'^api/1/recording_schedules/$', recording_schedules, name="recording_schedules"),
    re_path(r'^api/1/submit_recorder/$', submit_recorder, name="submit_recorder"),

    re_path(r'^api/2/', include(('radioco.apps.api.urls', 'api'), namespace="api"), name="api"),
]

if (settings.TESTING_MODE or settings.DEBUG) and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

# Media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Static
urlpatterns += staticfiles_urlpatterns()

radio/apps/programmes/views.py
# Radioco - Broadcasting Radio Recording Scheduling system.
# Copyright (C) 2014  Iago Veloso Abalo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import datetime

from django.shortcuts import render, get_object_or_404

from apps.programmes.models import Episode, Programme, Role, Participant, NOT_SPECIFIED


def programme_detail(request, slug):
    programme = get_object_or_404(Programme, slug=slug)
    context = {
        'programme': programme, 'unspecified': NOT_SPECIFIED, 'language': programme.get_language_display(),
        'role_list': Role.objects.filter(programme=programme).select_related('person__userprofile', 'programme'),
        'episode_list': Episode.objects.filter(
            programme=programme
        ).select_related('programme').order_by('-season', '-number_in_season')
    }
    return render(request, 'programmes/programme_detail.html', context)


def episode_detail(request, slug, season_number, episode_number):
    programme = get_object_or_404(Programme, slug=slug)
    episode = None
    episode_end_date = None
    try:
        episode = Episode.objects.select_related(
            'podcast', 'programme'
        ).get(programme=programme, season=season_number, number_in_season=episode_number)
        episode_end_date = episode.issue_date + episode.runtime + datetime.timedelta(hours=1)
    except:
        pass
    context = {
        'episode': episode, 'programme': programme, 'now': datetime.datetime.now(),
        'episode_end_date': episode_end_date,
        'role_list': Participant.objects.filter(episode=episode).select_related('person__userprofile'),
        'unspecified': NOT_SPECIFIED
    }
    return render(request, 'programmes/episode_detail.html', context)

radioco/apps/programmes/views.py
# Radioco - Broadcasting Radio Recording Scheduling system.
# Copyright (C) 2014  Iago Veloso Abalo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import datetime
from django.db.models import Q

from django.shortcuts import render, get_object_or_404
from django.utils import timezone

from radioco.apps.programmes.models import Episode, Programme, Role, Participant


def get_filtered_programmes(name, category, isActiveParam):
    isActive = True if isActiveParam == 'on' else False
    today = timezone.now()

    if (isActive):
        filterParam = (Q(end_date=None) | Q(end_date__gte=today)) & Q(name__icontains=name) & Q(category__icontains=category)
    else:
        filterParam = Q(end_date__lt=today) & Q(name__icontains=name) & Q(category__icontains=category)

    filteredPrograms = Programme.objects.order_by('name').filter(filterParam)
    return filteredPrograms


def programme_search(request):
    if request.method == 'POST':
        name = request.POST.get('name', '')
        category = request.POST.get('category', '')
        isActiveParam = request.POST.get('isActiveParam', 'off')

        context = {
            'programme_list': get_filtered_programmes(name, category, isActiveParam),
            'name': name,
            'category': category,
            'isActiveParam': isActiveParam,
            'categories': Programme.CATEGORY_CHOICES,
        }
    else:
        name = request.GET.get('name', '')
        category = request.GET.get('category', '')
        isActiveParam = request.GET.get('isActiveParam', 'on')

        context = {
            'programme_list': get_filtered_programmes(name, category, isActiveParam),
            'name': name,
            'category': category,
            'isActiveParam': isActiveParam,
            'categories': Programme.CATEGORY_CHOICES,
        }
    return render(request, 'programmes/programme_list.html', context)


def programme_detail(request, slug):
    programme = get_object_or_404(Programme, slug=slug)
    context = {
        'programme': programme, 'language': programme.get_language_display(),
        'role_list': Role.objects.filter(programme=programme).select_related('person__userprofile', 'programme'),
        'episode_list': Episode.objects.filter(
            programme=programme
        ).select_related('programme').order_by('-season', '-number_in_season')
    }
    return render(request, 'programmes/programme_detail.html', context)


def episode_detail(request, slug, season_number, episode_number):
    programme = get_object_or_404(Programme, slug=slug)
    episode = None
    episode_end_date = None
    try:
        episode = Episode.objects.select_related(
            'podcast', 'programme'
        ).get(programme=programme, season=season_number, number_in_season=episode_number)
        # TODO: why am I adding 1 hour?
        episode_end_date = episode.issue_date + episode.runtime + datetime.timedelta(hours=1)
    except:
        pass
    context = {
        'episode': episode, 'programme': programme, 'now': timezone.now(),
        'episode_end_date': episode_end_date,
        'role_list': Participant.objects.filter(episode=episode).select_related('person__userprofile')
    }
    return render(request, 'programmes/episode_detail.html', context)

radioco/apps/programmes/templates/programmes/episode_detail.html
{% extends "radioco/base.html" %}
{% load staticfiles i18n disqus_tags %}


{% block extra_head %}
    <link rel="alternate" type="application/atom+xml" title="RSS Feed for {{ episode.programme.name }}" href="{% url 'programmes:rss' episode.programme.slug %}" />
{% endblock %}

{% block page_title %}{{ episode }}{% endblock %}

{% block programmes_class %}active{% endblock %}

{% block content %}
    <div class="container mb">
        <div class="row">
            <div class="col-lg-10 offset-lg-1 centered">
                <img class="center-block img-responsive" src="{{ programme.photo.url }}" alt="...">
            </div>

            <div class="col-lg-5 offset-lg-1 spacing">
                <h4>{{ episode|title }}</h4>

                <p>{% firstof episode.summary|safe episode.programme.synopsis|safe '' %}</p>

                <h4>{% trans "Podcast" %}</h4>
                <p class="podcast-download">
                    {% if episode.podcast %}
                        <audio src="{{ episode.podcast.url }}" type="{{ episode.podcast.mime_type }}" controls>
                            {% trans "Your browser does not support the audio element." %}
                        </audio>
                        <a href="{{ episode.podcast.url }}" target="_blank" download>
                          <span class="fa fa-download fa-2x"></span>
                        </a>
                    {% else %}
                        {% if not episode_end_date or now > episode_end_date %}
                            {% trans "Sorry, this podcast isn't available yet" %}
                        {% else %}
                            {% trans "The podcast will be available in" %} {{ episode_end_date|timeuntil }}
                        {% endif %}
                    {% endif %}
                </p>
            </div>

            <div class="col-lg-4 offset-lg-1 spacing">
                <h4>{% trans 'Programme Details' %}</h4>
                <div class="hline"></div>
                <p>
                    <b>{% trans 'Date:' %}</b>
                    {% if episode.issue_date %}
                        {{ episode.issue_date|date:"DATETIME_FORMAT" }}
                    {% else %}
                        {% trans "Schedule pending" %}
                    {% endif %}
                </p>
                <p>
                    <b>{% trans 'Programme:' %}</b>
                    <a href="{% url 'programmes:detail' programme.slug %}">{{ programme.name }}</a>
                </p>
                <p>
                    <b>{% trans 'Category:' %}</b>
                    {{ programme.get_category_display }}
                </p>
                <p>
                    <b>{% trans 'RSS:' %}</b>
                    <a rel="alternate" type="application/atom+xml" href="pcast://{{ request.get_host }}{% url 'programmes:rss' programme.slug %}">
                        <i class="fa fa-rss-square fa-2x"></i>
                    </a>
                </p>
            </div>

        </div>
        <! --/row -->
        {% if settings.DISQUS_ENABLE %}
            <div class="row">
                <div class="col-lg-10 offset-lg-1 centered">
                    {% set_disqus_identifier programme.id|stringformat:"i" %}
                    {% set_disqus_title programme.name %}
                    {% set_disqus_url episode.get_absolute_url %}
                    {% disqus_show_comments %}
                </div>
            </div>
        {% endif %}
    </div><! --/container -->

    {% if role_list %}
        <div class="container mhtb">
            <div class="row centered">
                <h3 class="mb">{% trans 'Participants'|upper %}</h3>
                {% for role in role_list %}
                    {% include "programmes/role_snippet.html" %}
                {% endfor %}
            </div>
        </div>
    {% endif %}

{% endblock %}

radioco/apps/programmes/templates/programmes/programme_detail.html
{% extends "radioco/base.html" %}
{% load staticfiles i18n disqus_tags %}


{% block extra_head %}
    <link rel="alternate" type="application/atom+xml" title="RSS Feed for {{ programme.name }}" href="{% url 'programmes:rss' programme.slug %}" />
{% endblock %}

{% block page_title %}{{ programme.name }}{% endblock %}

{% block programmes_class %}active{% endblock %}

{% block content %}
    <div class="container mb">
        <div class="row">
            <div class="col-lg-10 offset-lg-1 centered">
                <img class="center-block img-responsive" src="{{ programme.photo.url }}" alt="...">
            </div>

            <div class="col-lg-5 offset-lg-1 spacing">
                <h4>{{ programme.name }}</h4>
                <p>{{ programme.synopsis|safe }}</p>
            </div>

            <div class="col-lg-4 offset-lg-1 spacing">
                <h4>{% trans 'Programme Details' %}</h4>
                <div class="hline"></div>
                <p><b>Language:</b> {{ language }}</p>
                <p><b>Category:</b> {{ programme.get_category_display }}</p>
                <p>
                    <b>RSS:</b>
                    <a rel="alternate" type="application/atom+xml" href="pcast://{{ request.get_host }}{% url 'programmes:rss' programme.slug %}">
                        <i class="fa fa-rss-square fa-2x"></i>
                    </a>
                </p>
            </div>

        </div>
        {% if settings.DISQUS_ENABLE %}
            <div class="row mhb">
                <div class="col-lg-10 offset-lg-1 centered">
                    {% set_disqus_identifier programme.id|stringformat:"i" %}
                    {% set_disqus_title programme.name %}
                    {% set_disqus_url programme.get_absolute_url %}
                    {% disqus_show_comments %}
                </div>
            </div>
        {% endif %}
    </div><! --/container -->

    {% if episode_list %}
        <div class="container mhb">
            <div class="row">
                <h3 class="text-center">{% trans 'Episodes' %}</h3>
                {% for episode in episode_list %}

                    {% ifchanged episode.season %}
                        {% if not forloop.first %}</div> {% endif %}
                        <div class="col-lg-3">
                            <h4>{% trans "Season" %} {{ episode.season }}</h4>
                            <div class="hline"></div>
                    {% endifchanged %}
                    <p>
                        <a href="{% url 'programmes:episode_detail' programme.slug episode.season episode.number_in_season %}">
                            {{ episode }}
                        </a>
                    </p>
                    {% if forloop.last %}</div>{% endif %}

                {% endfor %}
            </div>
        </div>
    {% endif %}

    {% if role_list %}
        <div class="container mhb">
            <div class="row centered">
                <h3 class="mb">MEMBERS</h3>
                {% for role in role_list %}
                    {% include "programmes/role_snippet.html" %}
                {% endfor %}
            </div>
        </div>
    {% endif %}

{% endblock %}

radioco/apps/programmes/templates/programmes/programme_list.html
{% extends "radioco/base.html" %}
{% load staticfiles i18n fb_versions %}
{% load i18n %}

{% block page_title %}{% trans "Programme list" %}{% endblock %}

{% block programmes_class %}active{% endblock %}

{% block content %}
    <div class="container mb">

        <div class="mb">
            <form method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input
                        name="name"
                        type="text"
                        class="form-control col-md-6 mr-4"
                        placeholder="{% trans 'Type to search' %}"
                        aria-label="Search"
                        value="{{ name }}"
                    />
                    <select
                        name="category"
                        class="custom-select col-md-3 mr-4"
                        value="{{ category }}"
                    >
                        <option value>{% trans 'Select a category...' %}</option>
                        {% for opt in categories %}
                            {% if category == "{{ opt.0 }}" %}
                                <option selected value="{{ opt.0 }}">{{ opt.0 }}</option>
                            {% else %}
                                <option value="{{ opt.0 }}">{{ opt.0 }}</option>
                            {% endif %}
                        {% endfor %}
                    </select>
                    <div class="custom-control custom-switch mr-3" style="margin: auto;">
                        {% if isActiveParam == "on" %}
                            <input
                                name="isActiveParam"
                                type="checkbox"
                                class="custom-control-input"
                                id="isActiveSwitch"
                                checked
                            />
                        {% else %}
                            <input
                                name="isActiveParam"
                                type="checkbox"
                                class="custom-control-input"
                                id="isActiveSwitch"
                            />
                        {% endif %}
                        <label class="custom-control-label" for="isActiveSwitch">{% trans 'Active programmes' %}</label>
                    </div>
                    <button type="submit" class="btn btn-primary">Search</button>
                </div>
            </form>
        </div>
    </div>

    {% for programme in programme_list %}
        <div class="container mb">
            <div class="row">
                <div class="col-lg-6">
                    <a href="{% url 'programmes:detail' programme.slug %}">
                        <img class="img-responsive" src="{% version programme.photo 'programme_preview' %}" alt="...">
                    </a>
                </div>

                <div class="col-lg-6">
                    <h4>{{ programme.name|title }}</h4>
                    <p>{{ programme.synopsis|truncatewords_html:130|safe }}</p>
                    <p>
                        <br/>
                        <a href="{{ programme.get_absolute_url }}" class="btn btn-theme">{% trans 'More Info' %}</a>
                    </p>
                </div>
            </div>
        </div><! --/container -->
    {% empty %}
        <h1>{% trans "No programmes are available"|upper %}</h1>
    {% endfor %}
{% endblock %}

radioco/apps/programmes/templates/programmes/role_snippet.html
{% load static i18n fb_versions %}


<div class="col-lg-3 col-md-3 col-sm-3">
    <div class="he-wrap tpl6">
        <img class="img-responsive" src="{% version role.person.userprofile.avatar 'person_preview' %}" alt="">
        <div class="he-view">
            <div class="bg a0" data-animate="fadeIn">
                <h3 class="a1" data-animate="fadeInDown">{% firstof role.person.get_full_name role.person %}</h3>
                {% if role.person.userprofile.display_personal_page %}
                    <a href="{% url 'users:detail' role.person.userprofile.slug %}" class="dmbutton a2" data-animate="fadeInUp">
                        <i class="fa fa-search"></i>
                    </a>
                {% endif %}
                <h5 class="a1" data-animate="fadeInDown">{{ role.role }}</h5>
            </div><!-- he bg -->
        </div><!-- he view -->
    </div><!-- he wrap -->
    <h4>{% firstof role.person.get_full_name role.person %}</h4>
    {% if role.role %}
        <h5 class="ctitle">{{ role.role }}</h5>
    {% endif %}
    <p>{{ role.description|truncatewords_html:20|safe }}</p>
    <div class="hline"></div>
</div><! --/col-lg-3 -->