radio/apps/programmes/urls.py
# Radioco - Broadcasting Radio Recording Scheduling system.
# Copyright (C) 2014  Iago Veloso Abalo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf.urls import patterns, url
from django.views.generic import ListView

from apps.programmes import views
from apps.programmes.feeds import RssProgrammeFeed
from apps.programmes.models import Programme

urlpatterns = patterns('',
   url(
       r'^$',
       ListView.as_view(
           queryset=Programme.objects.order_by('name'),
           template_name='programmes/programme_list.html'
       ),
       name='list'
   ),
   url(r'^(?P<slug>[-\w]+)/$', views.programme_detail, name='detail'),
   url(
       r'^(?P<slug>[-\w]+)/(?P<season_number>\d+)x(?P<episode_number>\d+)/$',
       views.episode_detail,
       name='episode_detail'
   ),
   url(r'^(?P<slug>[-\w]+)/rss/$', RssProgrammeFeed(), name='rss')
)

radio/configs/common/urls.py
# Radioco - Broadcasting Radio Recording Scheduling system.
# Copyright (C) 2014  Iago Veloso Abalo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _
from filebrowser.sites import site

admin.site.logout_template = 'radio/logged_out.html'
admin.site.site_header = _('RadioCo administration')
admin.site.site_title = _('RadioCo site admin')


def handler400(request):
    response = render_to_response('radio/400.html', {}, context_instance=RequestContext(request))
    response.status_code = 400
    return response


def handler404(request):
    response = render_to_response('radio/404.html', {}, context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler403(request):
    response = render_to_response('radio/403.html', {}, context_instance=RequestContext(request))
    response.status_code = 403
    return response


def handler500(request):
    response = render_to_response('radio/500.html', {}, context_instance=RequestContext(request))
    response.status_code = 500
    return response


urlpatterns = patterns('',
    url(r'^$', 'apps.radio.views.index', name="home"),
    url(r'^login/$', 'apps.radio.views.user_login', name="login"),
    url(r'^logout/$', 'apps.radio.views.user_logout', name="logout"),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^configuration/schedule_editor/', 'apps.dashboard.views.full_calendar', name="schedule_editor"),
    url(r'^schedules/', include('apps.schedules.urls', namespace="schedules")),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace="dashboard")),
    url(r'^programmes/', include('apps.programmes.urls', namespace="programmes")),
    url(r'^users/', include('apps.users.urls', namespace="users")),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^api/1/recording_schedules/$', 'apps.radio.views.recording_schedules', name="recording_schedules"),
    url(r'^api/1/radiocom/programmes', 'apps.api.views.programmes_json', name='programmes_json'),
    url(r'^api/1/radiocom/radiostation', 'apps.api.views.station_json', name='station_json'),
    url(r'^api/1/submit_recorder/$', 'apps.radio.views.submit_recorder', name="submit_recorder"),
    url(r'^api/2/', include('apps.api.urls', namespace="api"))
)

if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

# Media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Static
urlpatterns += staticfiles_urlpatterns()

radioco/apps/api/urls.py
from rest_framework import routers
from radioco.apps.api import views
from django.urls import include, re_path


router = routers.DefaultRouter(trailing_slash=False)
router.register(r'programmes', views.ProgrammeViewSet)
router.register(r'episodes', views.EpisodeViewSet)
router.register(r'schedules', views.ScheduleViewSet)
router.register(r'transmissions', views.TransmissionViewSet, basename='transmission')
router.register(r'operations', views.TransmissionOperationViewSet, basename='operation')

radiocom_router = routers.DefaultRouter(trailing_slash=False)
radiocom_router.register(r'programmes', views.RadiocomProgrammeViewSet, basename='radiocom_programmes')
radiocom_router.register(r'transmissions', views.RadiocomTransmissionViewSet, basename='radiocom_transmission')
radiocom_router.register(r'radiostation', views.RadiocomStation, basename='radiocom_radiostation')

urlpatterns = router.urls + [
    re_path(r'^radiocom/', include(radiocom_router.urls)),
]

radioco/configs/base/urls.py
# Radioco - Broadcasting Radio Recording Scheduling system.
# Copyright (C) 2014  Iago Veloso Abalo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf import settings
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils.translation import gettext_lazy as _
from django.views.i18n import JavaScriptCatalog
from filebrowser.sites import site

admin.site.logout_template = 'radioco/logged_out.html'
admin.site.site_header = _('RadioCo administration')
admin.site.site_title = _('RadioCo site admin')


### templates not implemented, led to strange exceptions when running tests.
# def handler400(request):
#    response = render_to_response('radioco/400.html', {}, context_instance=RequestContext(request))
#    response.status_code = 400
#    return response
#
#
# def handler404(request):
#    response = render_to_response('radioco/404.html', {}, context_instance=RequestContext(request))
#    response.status_code = 404
#    return response
#
#
# def handler403(request):
#    response = render_to_response('radioco/403.html', {}, context_instance=RequestContext(request))
#    response.status_code = 403
#    return response
#
#
# def handler500(request):
#    response = render_to_response('radioco/500.html', {}, context_instance=RequestContext(request))
#    response.status_code = 500
#    return response

js_info_dict = {
    'packages': ('recurrence',),
}

from radioco.apps.radioco.views import index, user_logout
from radioco.apps.api.recorder_views import recording_schedules, submit_recorder

urlpatterns = [
    re_path(r'^$', index, name="home"),
    re_path(r'^jsi18n/$', JavaScriptCatalog.render_to_response, js_info_dict, name='javascript-catalog'),
    re_path(r'^logout/$', user_logout, name="logout"),
    # re_path(r'^admin/filebrowser/', include(site.urls)),
    re_path(r'^admin/filebrowser/', site.urls),
    re_path(r'^grappelli/', include('grappelli.urls')),
    # re_path(r'^admin/', include(admin.site.urls)),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^admin/password_reset/$', auth_views.PasswordResetView.as_view(), name='admin_password_reset'),
    re_path(r'^admin/password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # url(r'^configuration/schedule_editor/', 'radioco.apps.dashboard.views.full_calendar', name="schedule_editor"),
    re_path(r'^schedules/', include(('radioco.apps.schedules.urls', 'schedules'), namespace="schedules"), name="schedules"),
    re_path(r'^programmes/', include(('radioco.apps.programmes.urls', 'programmes'), namespace="programmes"), name="programmes"),
    re_path(r'^users/', include(('radioco.apps.users.urls', 'users'), namespace="users"), name="users"),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    re_path(r'^api/1/recording_schedules/$', recording_schedules, name="recording_schedules"),
    re_path(r'^api/1/submit_recorder/$', submit_recorder, name="submit_recorder"),

    re_path(r'^api/2/', include(('radioco.apps.api.urls', 'api'), namespace="api"), name="api"),
]

if (settings.TESTING_MODE or settings.DEBUG) and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

# Media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Static
urlpatterns += staticfiles_urlpatterns()

radio/apps/api/views.py
# Radioco - Broadcasting Radio Recording Scheduling system.
# Copyright (C) 2014  Iago Veloso Abalo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import serializers
import json
import re

from apps.programmes.models import Programme
from apps.global_settings.models import RadiocomConfiguration
from apps.global_settings.models import SiteConfiguration
from rest_framework import viewsets
from django.http import HttpResponse


class ProgrammeViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Programme.objects.all()
    serializer_class = serializers.ProgrammeSerializer


def programmes_json(request):
    url = re.sub(request.get_full_path(), '', request.build_absolute_uri())

    programme_list = Programme.objects.order_by('end_date', 'name')
    json_list = []

    for programme in programme_list:
        json_entry = {
            'id': programme.id,
            'genre': programme.get_category_display(),
            'title': programme.name,
            'description': programme.synopsis,
            'logo_url': url + programme.photo.url,
            'rss_url': url + "/programmes/" + programme.slug + '/rss/'
        }
        json_list.append(json_entry)

    data = {'data': json_list}

    return HttpResponse(json.dumps(data), content_type='application/json')


def station_json(request):

    radiocomConfiguration = RadiocomConfiguration.objects.get()
    siteConfiguration = SiteConfiguration.objects.get()

    # tokenizer station_photos by ',' to generate a list
    list_photos = []
    for word in radiocomConfiguration.station_photos.split(','):
        list_photos.append(word.strip())

    json_list = []
    json_entry = {
        'id': radiocomConfiguration.id,
        'station_name': radiocomConfiguration.station_name,
        'icon_url': radiocomConfiguration.big_icon_url,
        'big_icon_url': radiocomConfiguration.big_icon_url,
        'history': radiocomConfiguration.history,
        'latitude': radiocomConfiguration.latitude,
        'longitude': radiocomConfiguration.longitude,
        'news_rss': radiocomConfiguration.news_rss,
        'station_photos': list_photos,
        'stream_url': radiocomConfiguration.stream_url,
        'facebook_url': siteConfiguration.facebook_address,
        'twitter_url': siteConfiguration.twitter_address
    }
    json_list.append(json_entry)

    data = {'data': json_list}

    return HttpResponse(json.dumps(data), content_type='application/json')

radio/apps/programmes/views.py
# Radioco - Broadcasting Radio Recording Scheduling system.
# Copyright (C) 2014  Iago Veloso Abalo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


import datetime

from django.shortcuts import render, get_object_or_404

from apps.programmes.models import Episode, Programme, Role, Participant, NOT_SPECIFIED


def programme_detail(request, slug):
    programme = get_object_or_404(Programme, slug=slug)
    context = {
        'programme': programme, 'unspecified': NOT_SPECIFIED, 'language': programme.get_language_display(),
        'role_list': Role.objects.filter(programme=programme).select_related('person__userprofile', 'programme'),
        'episode_list': Episode.objects.filter(
            programme=programme
        ).select_related('programme').order_by('-season', '-number_in_season')
    }
    return render(request, 'programmes/programme_detail.html', context)


def episode_detail(request, slug, season_number, episode_number):
    programme = get_object_or_404(Programme, slug=slug)
    episode = None
    episode_end_date = None
    try:
        episode = Episode.objects.select_related(
            'podcast', 'programme'
        ).get(programme=programme, season=season_number, number_in_season=episode_number)
        episode_end_date = episode.issue_date + episode.runtime + datetime.timedelta(hours=1)
    except:
        pass
    context = {
        'episode': episode, 'programme': programme, 'now': datetime.datetime.now(),
        'episode_end_date': episode_end_date,
        'role_list': Participant.objects.filter(episode=episode).select_related('person__userprofile'),
        'unspecified': NOT_SPECIFIED
    }
    return render(request, 'programmes/episode_detail.html', context)

radio/apps/radio/templates/radio/index.html
{% extends "radio/base.html" %}
{% load i18n staticfiles %}
{% load global_settings_extras fb_versions %}
{% get_global_model 'global_settings.SiteConfiguration' as site_config %}


{% block meta_title %}{% trans "Home" %}{% endblock %}

{% block page_title_wrapper %}{% endblock %}

{% block content %}

    <!-- *****************************************************************************************************************
	 HEADERWRAP
	 ***************************************************************************************************************** -->
    <div id="headerwrap">
        <div class="container">
            <div class="row">
                {% if schedule_now %}
                    <div class="col-lg-8 col-lg-offset-2">
                        <h1>{% trans "On air"|upper %}</h1>
                        <h3>
                            <a href="{% url 'programmes:detail' schedule_now.programme.slug %}">
                                {{ schedule_now.programme.name }}
                            </a>
                        </h3>
                        <h5>
                            <strong>{{ start_time|date:"G:i" }} - {{ end_time|date:"G:i" }}</strong>
                        </h5>

                        <div class="progress">
                            <div class="progress-bar progress-bar-success" role="progressbar"
                                 aria-valuenow="{{ percentage }}" aria-valuemin="0" aria-valuemax="100"
                                 style="width: {{ percentage }}%">
                                <span class="sr-only">{{ percentage }}% Complete (success)</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-8 col-lg-offset-2 himg">
                        <a href="{{ schedule_now.programme.get_absolute_url }}">
                            <img src="{{ schedule_now.programme.photo.url }}" class="img-responsive img-thumbnail">
                        </a>
                    </div>
                {% else %}
                    <div class="col-lg-8 col-lg-offset-2">
                        <h3>{% trans 'There are currently no programmes on air' %}</h3>
                        <h1>{% trans 'Check all our programmes' %}</h1>
                        <h5><a href="{% url 'programmes:list' %}" class="btn btn-theme">{% trans 'See all' %}</a></h5>
                    </div>
                {% endif %}
            </div><!-- /row -->
        </div> <!-- /container -->
    </div><!-- /headerwrap -->

    <!-- *****************************************************************************************************************
     SERVICE LOGOS
     ***************************************************************************************************************** -->
    <div id="service">
        <div class="container">
            <div class="row centered">
                <div class="col-md-12">

                    <h1>{% trans "playlist"|upper %} {{ now|date:"DATE_FORMAT"|upper }}</h1>

                    <ul class="list-group">
                        {% if schedule_now %}
                            <li class="list-group-item list-group-item-info">
                                <h4>
                                    <span class="label label-danger">{% trans "Now"|upper %}</span>
                                    <a href="{% url 'programmes:detail' schedule_now.programme.slug %}">
                                        {{ schedule_now.programme.name }}
                                    </a>
                                </h4>
                            </li>
                        {% endif %}

                        {% for schedule, date, episode in next_events %}
                            <li class="list-group-item">
                                <h4>
                                    <span class="label label-success">{{ date|date:"G:i" }}</span>
                                    {% if episode %}
                                        <a href="{% url 'programmes:episode_detail' schedule.programme.slug episode.season episode.number_in_season %}">{{ schedule.programme.name }}</a>
                                    {% else %}
                                        <a href="{% url 'programmes:detail' schedule.programme.slug %}">{{ schedule.programme.name }}</a>
                                    {% endif %}
                                </h4>
                            </li>
                        {% endfor %}
                        {% if not next_events and not schedule_now %}
                            <h4>{% trans "There are currently no programmes"|upper %}</h4>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div><! --/service -->

    <!-- *****************************************************************************************************************
     PORTFOLIO SECTION
     ***************************************************************************************************************** -->
    {% if other_programmes %}
        <div id="portfoliowrap">
            {% trans 'Our programmes' as our_programmes %}
            <h3>{{ our_programmes|upper }}</h3>

            <div class="portfolio-centered">
                <div class="recentitems portfolio">

                    {% for programme in other_programmes %}
                        <div class="portfolio-item ">
                            <div class="he-wrap tpl6">
                                <img src="{% version programme.photo 'item_overlap' %}" alt="">
                                <div class="he-view">
                                    <div class="bg a0" data-animate="fadeIn">
                                        <h3 class="a1" data-animate="fadeInDown">{{ programme.name }}</h3>
                                        <a href="{{ programme.get_absolute_url }}" class="dmbutton a2" data-animate="fadeInLeft">
                                            <i class="fa fa-search"></i>
                                        </a>
                                        <a href="{% url 'programmes:rss' programme.slug %}" class="dmbutton a2" data-animate="fadeInRight">
                                            <i class="fa fa-rss"></i>
                                        </a>
                                        <h5 class="a1" data-animate="fadeInUp">{{ programme.get_category_display }}</h5>
                                    </div><!-- he bg -->
                                </div><!-- he view -->
                            </div><!-- he wrap -->
                        </div><!-- end col-12 -->
                    {% endfor %}

                </div><!-- portfolio -->
            </div><!-- portfolio container -->
        </div><!--/Portfoliowrap -->
    {% endif %}


    <!-- *****************************************************************************************************************
     MIDDLE CONTENT
     ***************************************************************************************************************** -->

    <div class="container mtb">
        <div class="row">
            <div class="col-lg-4 col-lg-offset-1">
                <h4>{% trans 'More About Us.' %}</h4>
                <p> {{ site_config.more_about_us }}</p>
            </div>

            <div class="col-lg-4 col-lg-offset-1">
                <h4>{% trans 'Latest Episodes' %}</h4>
                <div class="hline"></div>
                {% for episode in latest_episodes %}
                    <p>
                        <a href="{{ episode.get_absolute_url }}">{{ episode|title }}</a>
                    </p>
                {% empty %}
                    <p>{% trans "There are currently no podcast" %}</p>
                {% endfor %}
            </div>

        </div>
    </div><! --/container -->

{% endblock %}