radio/configs/common/urls.py
# Radioco - Broadcasting Radio Recording Scheduling system.
# Copyright (C) 2014  Iago Veloso Abalo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _
from filebrowser.sites import site

admin.site.logout_template = 'radio/logged_out.html'
admin.site.site_header = _('RadioCo administration')
admin.site.site_title = _('RadioCo site admin')


def handler400(request):
    response = render_to_response('radio/400.html', {}, context_instance=RequestContext(request))
    response.status_code = 400
    return response


def handler404(request):
    response = render_to_response('radio/404.html', {}, context_instance=RequestContext(request))
    response.status_code = 404
    return response


def handler403(request):
    response = render_to_response('radio/403.html', {}, context_instance=RequestContext(request))
    response.status_code = 403
    return response


def handler500(request):
    response = render_to_response('radio/500.html', {}, context_instance=RequestContext(request))
    response.status_code = 500
    return response


urlpatterns = patterns('',
    url(r'^$', 'apps.radio.views.index', name="home"),
    url(r'^login/$', 'apps.radio.views.user_login', name="login"),
    url(r'^logout/$', 'apps.radio.views.user_logout', name="logout"),
    url(r'^admin/filebrowser/', include(site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    # url(r'^configuration/schedule_editor/', 'apps.dashboard.views.full_calendar', name="schedule_editor"),
    url(r'^schedules/', include('apps.schedules.urls', namespace="schedules")),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace="dashboard")),
    url(r'^programmes/', include('apps.programmes.urls', namespace="programmes")),
    url(r'^users/', include('apps.users.urls', namespace="users")),

    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

    url(r'^api/1/recording_schedules/$', 'apps.radio.views.recording_schedules', name="recording_schedules"),
    url(r'^api/1/radiocom/programmes', 'apps.api.views.programmes_json', name='programmes_json'),
    url(r'^api/1/radiocom/radiostation', 'apps.api.views.station_json', name='station_json'),
    url(r'^api/1/submit_recorder/$', 'apps.radio.views.submit_recorder', name="submit_recorder"),
    url(r'^api/2/', include('apps.api.urls', namespace="api"))
)

if settings.DEBUG and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )

# Media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Static
urlpatterns += staticfiles_urlpatterns()

radioco/apps/api/urls.py
from rest_framework import routers
from radioco.apps.api import views
from django.urls import include, re_path


router = routers.DefaultRouter(trailing_slash=False)
router.register(r'programmes', views.ProgrammeViewSet)
router.register(r'episodes', views.EpisodeViewSet)
router.register(r'schedules', views.ScheduleViewSet)
router.register(r'transmissions', views.TransmissionViewSet, basename='transmission')
router.register(r'operations', views.TransmissionOperationViewSet, basename='operation')

radiocom_router = routers.DefaultRouter(trailing_slash=False)
radiocom_router.register(r'programmes', views.RadiocomProgrammeViewSet, basename='radiocom_programmes')
radiocom_router.register(r'transmissions', views.RadiocomTransmissionViewSet, basename='radiocom_transmission')
radiocom_router.register(r'radiostation', views.RadiocomStation, basename='radiocom_radiostation')

urlpatterns = router.urls + [
    re_path(r'^radiocom/', include(radiocom_router.urls)),
]

radioco/apps/users/urls.py
# Radioco - Broadcasting Radio Recording Scheduling system.
# Copyright (C) 2014  Iago Veloso Abalo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.urls import re_path

from radioco.apps.users import views

urlpatterns = [
    re_path(r'^$', views.UsersView.as_view(), name='list'),
    re_path(r'^(?P<slug>[-\w]+)/$', views.userprofile_detail, name='detail'),
]

radioco/configs/base/urls.py
# Radioco - Broadcasting Radio Recording Scheduling system.
# Copyright (C) 2014  Iago Veloso Abalo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from django.conf import settings
from django.urls import include, re_path
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.utils.translation import gettext_lazy as _
from django.views.i18n import JavaScriptCatalog
from filebrowser.sites import site

admin.site.logout_template = 'radioco/logged_out.html'
admin.site.site_header = _('RadioCo administration')
admin.site.site_title = _('RadioCo site admin')


### templates not implemented, led to strange exceptions when running tests.
# def handler400(request):
#    response = render_to_response('radioco/400.html', {}, context_instance=RequestContext(request))
#    response.status_code = 400
#    return response
#
#
# def handler404(request):
#    response = render_to_response('radioco/404.html', {}, context_instance=RequestContext(request))
#    response.status_code = 404
#    return response
#
#
# def handler403(request):
#    response = render_to_response('radioco/403.html', {}, context_instance=RequestContext(request))
#    response.status_code = 403
#    return response
#
#
# def handler500(request):
#    response = render_to_response('radioco/500.html', {}, context_instance=RequestContext(request))
#    response.status_code = 500
#    return response

js_info_dict = {
    'packages': ('recurrence',),
}

from radioco.apps.radioco.views import index, user_logout
from radioco.apps.api.recorder_views import recording_schedules, submit_recorder

urlpatterns = [
    re_path(r'^$', index, name="home"),
    re_path(r'^jsi18n/$', JavaScriptCatalog.render_to_response, js_info_dict, name='javascript-catalog'),
    re_path(r'^logout/$', user_logout, name="logout"),
    # re_path(r'^admin/filebrowser/', include(site.urls)),
    re_path(r'^admin/filebrowser/', site.urls),
    re_path(r'^grappelli/', include('grappelli.urls')),
    # re_path(r'^admin/', include(admin.site.urls)),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^admin/password_reset/$', auth_views.PasswordResetView.as_view(), name='admin_password_reset'),
    re_path(r'^admin/password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    re_path(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # url(r'^configuration/schedule_editor/', 'radioco.apps.dashboard.views.full_calendar', name="schedule_editor"),
    re_path(r'^schedules/', include(('radioco.apps.schedules.urls', 'schedules'), namespace="schedules"), name="schedules"),
    re_path(r'^programmes/', include(('radioco.apps.programmes.urls', 'programmes'), namespace="programmes"), name="programmes"),
    re_path(r'^users/', include(('radioco.apps.users.urls', 'users'), namespace="users"), name="users"),

    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    re_path(r'^api/1/recording_schedules/$', recording_schedules, name="recording_schedules"),
    re_path(r'^api/1/submit_recorder/$', submit_recorder, name="submit_recorder"),

    re_path(r'^api/2/', include(('radioco.apps.api.urls', 'api'), namespace="api"), name="api"),
]

if (settings.TESTING_MODE or settings.DEBUG) and 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar
    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

# Media
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Static
urlpatterns += staticfiles_urlpatterns()

radio/radio/libs/home/templates/home/base.html
{% load staticfiles i18n %}
{% load global_settings_extras %}
{% get_global_model 'global_settings.SiteConfiguration' as site_config %}
<!DOCTYPE html>
<html>
	<head>
		{% block meta_tags %}{% endblock %}
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>
			{% block title %}{{ site_config.site_name }}{% endblock %}
		</title>
		{% block stylesheets %}
			<link rel="stylesheet" href="{% static "radio/css/bootstrap.min.css" %}" type="text/css" />
			<link rel="stylesheet" href="{% static "radio/css/jumbotron.css" %}" type="text/css" />
			<link rel="stylesheet" href="{% static "radio/css/sticky-footer.css" %}" type="text/css" />
			<link rel="stylesheet" href="{% static "radio/css/radioco.css" %}" type="text/css" />
		{% endblock %}
		{% block javascript %}
			<script src="{% static "radio/js/jquery-2.1.0.min.js" %}" type="text/javascript"></script>
			<script src="{% static "radio/js/bootstrap.min.js" %}" type="text/javascript"></script>
		{% endblock %}
		{% block extra_head %}{% endblock %}
	</head>
	<body>
		<!-- Fixed navbar -->
		<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="/">{{ site_config.site_name }}</a>
				</div>
				<div class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li {% block index_class %}{% endblock %}><a href="/">{% trans "home"|title %}</a></li>
						<li {% block schedules_class %}{% endblock %}><a href="{% url 'schedules:list' %}">{% trans "schedules"|title %}</a></li>
						<li {% block programmes_class %}{% endblock %}><a href="{% url 'programmes:list' %}">{% trans "programmes"|title %}</a></li>
						<li {% block users_class %}{% endblock %}><a href="{% url 'users:list' %}">{% trans "people"|title %}</a></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						{% if user.is_authenticated %}
						    <li><a href="{% url 'logout' %}">{% trans "Logout"|title %}</a></li>
						{% else %}
						    <li {% block login_class %}{% endblock %}><a href="{% url 'login' %}">{% trans "Log in"|title %}</a></li>
						{% endif %}
		            </ul>
				</div>
				<!--/.nav-collapse -->
			</div>
		</div>
		{% block header_content %}{% endblock %}
		<div class="container">
			{% block content %}
			{% endblock %}
		</div>
		<!-- /container -->
		<div class="footer">
			<div class="container">
				<p class="text-muted"><a href="http://radioco.org/" target="_blank"> <span class="glyphicon glyphicon-wrench"></span> RadioCo</a></p>
			</div>
		</div>
	</body>
</html>